In [22]:
import numpy as np
import time

In [23]:
m = 512
n = 512
A = np.random.rand(m,n)
I = np.identity(m)

In [24]:
A

array([[0.16333819, 0.05620854, 0.87424551, ..., 0.12556781, 0.21545743,
        0.29027476],
       [0.77957172, 0.35279323, 0.87849468, ..., 0.57905165, 0.72816895,
        0.86843083],
       [0.48246259, 0.40139285, 0.09864488, ..., 0.15701394, 0.84140243,
        0.46276828],
       ...,
       [0.43586886, 0.00863544, 0.91868888, ..., 0.75261821, 0.14695979,
        0.09176139],
       [0.23207097, 0.32949761, 0.43672869, ..., 0.9481808 , 0.94801342,
        0.92967033],
       [0.82136214, 0.65860633, 0.69581362, ..., 0.65364395, 0.68194142,
        0.56256727]])

In [25]:
k = min(m,n)
Q = np.identity(m)
vs = []     # Store Householder vectors instead of computing again for Q
start = time.time()
for i in range(k):
    x = A[i:m,i]
    sign = 1 if x[0] == 0 else np.sign(x[0])
    v = sign * np.linalg.norm(x) * I[i:m,i] + x             # 2(m-i)
    v = v / np.linalg.norm(v)                               # (m-i) + (m-i) + (m-i-1) + 1
    vs.append(v)
    A[i:m,i:n] -= 2 * np.outer(v, np.dot(v, A[i:m,i:n]))    # 4(m-i)*(n-i)

for i in range(k-1, -1, -1):          # i = k-1 downto 0 for Q backward sub
    v = vs[i]
    Q[i:m,i:m] -= 2 * np.outer(v, np.dot(v, Q[i:m,i:m]))    # 4(m-i)^2

end = time.time()

In [26]:
A[:,0]

array([-1.33614557e+01, -7.77156117e-16, -5.55111512e-16, -9.99200722e-16,
       -9.99200722e-16, -7.77156117e-16, -8.88178420e-16, -1.73472348e-17,
       -1.11022302e-15, -8.88178420e-16, -5.55111512e-16, -2.77555756e-16,
       -2.22044605e-16, -7.77156117e-16, -4.44089210e-16, -1.04083409e-17,
       -1.11022302e-15, -5.55111512e-16, -2.77555756e-16, -7.77156117e-16,
       -6.66133815e-16, -3.46944695e-17, -8.88178420e-16, -2.77555756e-16,
       -7.80625564e-18, -8.88178420e-16, -1.11022302e-16, -7.77156117e-16,
       -7.77156117e-16, -4.99600361e-16, -5.55111512e-16, -1.11022302e-15,
       -1.11022302e-15, -5.55111512e-16, -9.99200722e-16, -4.85722573e-17,
       -7.77156117e-16, -5.55111512e-16, -7.77156117e-16, -8.88178420e-16,
       -6.66133815e-16, -3.88578059e-16, -6.66133815e-16, -9.99200722e-16,
       -5.55111512e-16, -1.11022302e-15, -4.44089210e-16, -9.99200722e-16,
       -6.66133815e-16, -9.99200722e-16, -4.44089210e-16, -9.99200722e-16,
       -5.55111512e-16, -

In [27]:
Q

array([[-0.01222458, -0.00770106,  0.09958984, ...,  0.05469625,
         0.07175335, -0.0002031 ],
       [-0.05834482, -0.0271328 ,  0.04672353, ...,  0.03893235,
        -0.01925563,  0.06958795],
       [-0.03610853,  0.0040474 , -0.03749335, ...,  0.0481218 ,
        -0.05823919,  0.01889313],
       ...,
       [-0.03262136, -0.0366427 ,  0.09055061, ...,  0.05371808,
         0.00075916, -0.00773152],
       [-0.01736869,  0.01747742,  0.02535961, ...,  0.01926024,
        -0.05665386, -0.0116174 ],
       [-0.0614725 ,  0.00407403,  0.00540732, ...,  0.03167427,
         0.03239159, -0.01721945]])

In [28]:
print((end-start))

0.15627098083496094
