In [96]:
"""
Solving Ax = b using LU Decomposition
"""

'\nSolving Ax = b using LU Decomposition\n'

In [97]:
import numpy as np
import matplotlib.pyplot as plt

In [98]:
# Take a known matrix A to validate the algorithm
A = np.array([[ 3.,  1.,  2.],
                   [ 6.,  6.,  3.],
                   [-3., 11.,  0.]])

In [99]:
# # Code cell to generate a random matrix A such that Ax = b has a unique solution

# # Constraint 1: Must be a square matrix (n x n)
# n = 3 

# # Generate a random matrix A and vector b (using integers for cleaner output)
# A = np.random.randint(-10, 10, size=(n, n))
# b = np.random.randint(-10, 10, size=n)

# # Constraint 2: Must be non-singular (Determinant != 0)
# # We use a while loop to regenerate A if the determinant happens to be exactly 0
# while np.linalg.det(A) == 0:
#     print("Generated a singular matrix. Regenerating...")
#     A = np.random.randint(-10, 10, size=(n, n))

# print("Valid Matrix A generated (det != 0):\n", A)
# print("\nVector b:\n", b)

In [100]:
def lu_packed(A):
    A = A.copy()
    m = len(A)
    flop = 0
    for i in range(m - 1):
        for j in range(i + 1, m):
            mult = A[j][i] / A[i][i]
            flop += 1
            for k in range(i + 1, m):
                A[j][k] -= mult * A[i][k]
                flop += 2
            A[j][i] = mult
    return A, flop

P, flop = lu_packed(A)
L = np.tril(P, -1) + np.eye(len(A))
U = np.triu(P)
print(np.allclose(L @ U, A), flop)

True 13


In [101]:
print("L = \n", L)
print("U = \n", U)

L = 
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  3.  1.]]
U = 
 [[ 3.  1.  2.]
 [ 0.  4. -1.]
 [ 0.  0.  5.]]


In [102]:
# Now to solve Ax = b.
# LUx = b
# let Ux = y
# First solve Ly = b

# Defining b for the solution x = [1 2 3]
b = np.array((11, 27, 19))

m = A.shape[0]
y = np.zeros(m)

for i in range(m):
    y[i] = b[i]
    for j in range(i):
        y[i] -= y[j]*L[i][j]
    y[i] /= L[i][i]

# Once we have y, we solve Ux = y for x
x = np.zeros(m)
for i in range(m-1,-1,-1):
    x[i] = y[i]
    for j in range(i+1,m):
        x[i] -= x[j]*U[i][j]
    x[i] /= U[i][i]
print("Solution to LUx = b: ", x)

Solution to LUx = b:  [1. 2. 3.]


In [103]:
# Now lets try with a random matrix of size 512x512 to test the FlOpS equation (2*n^3/3)
n = 512
A = np.random.rand(n, n)

In [104]:
P, flop = lu_packed(A)
L = np.tril(P, -1) + np.eye(len(A))
U = np.triu(P)
print(np.allclose(L @ U, A), flop)

True 89347328


In [105]:
print(flop/(2*n**3/3))

0.9985342025756836
