In [1]:
import numpy as np
from scipy.linalg import lu, solve_triangular
import time

In [2]:
# -------------------------------
# Generate matrix and vector
# -------------------------------
#A = np.array([[2., 1., 1.],
#              [4., -6., 0.],
#              [-2., 7., 2.]])

#b = np.array([5., -2., 9.])
#n=A.shape[0]
n = 3  # Matrix size

A = np.random.rand(n, n)
b = np.random.rand(n)

In [3]:
# -------------------------------
# solve using LU Decomposition 
# -------------------------------
start = time.perf_counter()

# LU decomposition
P, L, U = lu(A)

# Forward substitution: Ly = Pb
y = solve_triangular(L, P @ b, lower=True)

# Back substitution: Ux = y
x = solve_triangular(U, y)

end = time.perf_counter()

elapsed = end - start


In [4]:
# -------------------------------
# FLOP estimation
# -------------------------------
# LU factorization      : (2/3)n^3
# Forward substitution  : n^2
# Back substitution     : n^2

flops = (2/3) * n**3 + 2 * n**2

performance = flops / elapsed
gflops = performance / 1e9

# -------------------------------
# Output
# -------------------------------
print(f"Matrix size              : {n} x {n}")
if(n<5):
	print("A =\n",A)
	print("P =\n", P)
	print("\nL =\n", L)
	print("\nU =\n", U)
	print("\nSolution x =")
	print(x)
print(f"Execution time           : {elapsed:.6f} seconds")
print(f"Estimated FLOPs          : {flops:.0f}")
print(f"Performance              : {performance:.3e} FLOPS")
print(f"Performance              : {gflops:.3e} GFLOPS")



Matrix size              : 3 x 3
A =
 [[0.22525652 0.38242625 0.78516223]
 [0.30035518 0.41215418 0.03480664]
 [0.77504713 0.01906387 0.94081993]]
P =
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

L =
 [[1.         0.         0.        ]
 [0.3875315  1.         0.        ]
 [0.2906359  0.93111895 1.        ]]

U =
 [[ 0.77504713  0.01906387  0.94081993]
 [ 0.          0.40476633 -0.32979072]
 [ 0.          0.          0.81880058]]

Solution x =
[1.17122436 0.83893383 0.00783028]
Execution time           : 0.001135 seconds
Estimated FLOPs          : 36
Performance              : 3.173e+04 FLOPS
Performance              : 3.173e-05 GFLOPS


In [5]:
#-----Solve using QR Decomposition----------------
start = time.perf_counter()

# QR decomposition
Q, R = np.linalg.qr(A)

# Compute Qᵀb
y = Q.T @ b

# Solve Rx = y
x = np.linalg.solve(R, y)

end = time.perf_counter()

elapsed = end - start

In [6]:
# ------------------------------------
# Performance calculations
# ------------------------------------
n = len(A)

# Approximate FLOPs
flops_qr = (4/3) * n**3          # QR decomposition
flops_qtb = 2 * n**2             # Matrix-vector multiplication
flops_backsolve = n**2           # Back substitution

total_flops = flops_qr + flops_qtb + flops_backsolve



gflops = total_flops / elapsed / 1e9

# ------------------------------------
# Output
# ------------------------------------
print(f"Matrix size              : {n} x {n}")
if(n<5):
    print("A =\n",A)
    print("Q =\n",Q)
    print("R =\n",R)
    print("Solution x =\n",x)


print(f"Execution time           : {elapsed:.6f} seconds")
print(f"Estimated FLOPs          : {total_flops:.0f}")
print(f"Performance              : {performance:.3e} FLOPS")
print(f"Performance              : {gflops:.3e} GFLOPS")
print("\nExecution time = {:.8f} s".format(elapsed))
print("Approximate FLOPs = {:.0f}".format(total_flops))
print("Performance = {:.6e} GFLOPS".format(gflops))

Matrix size              : 3 x 3
A =
 [[0.22525652 0.38242625 0.78516223]
 [0.30035518 0.41215418 0.03480664]
 [0.77504713 0.01906387 0.94081993]]
Q =
 [[-0.26156362 -0.63037369 -0.73089909]
 [-0.34876677 -0.64436635  0.680554  ]
 [-0.89997012  0.43292148 -0.0513106 ]]
R =
 [[-0.86119207 -0.26093139 -1.0642191 ]
 [ 0.         -0.49839657 -0.11007269]
 [ 0.          0.         -0.5984606 ]]
Solution x =
 [1.17122436 0.83893383 0.00783028]
Execution time           : 0.003356 seconds
Estimated FLOPs          : 63
Performance              : 3.173e+04 FLOPS
Performance              : 1.877e-05 GFLOPS

Execution time = 0.00335575 s
Approximate FLOPs = 63
Performance = 1.877375e-05 GFLOPS
